name: deploy with runner

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Installed dependencies
        run: npm install

      - name: build
        run: run run build --if-present
