name: Check ESlint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: Set token config
        run: |
          echo "@ronin:registry=https://ronin.supply/" > .npmrc
          echo "//ronin.supply/:_authToken=${secrets.RONIN_AUTH_TOKEN}" >> .npmrc
        env:
          secrets.RONIN_AUTH_TOKEN: ${{secrets.RONIN_AUTH_TOKEN}}

      - name: Install dependencies
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - name: Run lint
        run: npm run lint
