name: Check TS build

on: [push, pull_request]

jobs:
  test-tsc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm

      - name: Install dependencies
        run: npm install
      - name: Run test-tsc
        run: npm run test-tsc
