name: Check TS build

on: [push, pull_request]

jobs:
  test-tsc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.0.0
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install
      - name: Run test-tsc
        run: pnpm run test-tsc
