name: Check TS build

on: [push, pull_request]

jobs:
  typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
          env:
            NODE_ENV: production

      - name: Install dependencies
        run: npm install
      - name: Build contentlayer
        run: npm run build:contentlayer
      - name: Run typecheck
        run: npm run typecheck
